import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useLocomotiveScroll } from 'react-locomotive-scroll';

import styles from '../styles/main/main.module.css';

const About: NextPage = () => {

  const { scroll } = useLocomotiveScroll();
  
  return (
    <div className={styles.container}>
      <Head>
        <title>ABOUT - WRDLSS NEXT LOCOMOTION</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={[styles.main, ""].join(' ')}>
        <div data-scroll-section>

          <section id="firstSection" className={[styles.hero, "vh-100 dt w-100 bg-white relative z-0"].join(' ')} data-scroll data-scroll-speed="-8">
            <div className={[styles.heroContainer, "dtc v-mid tc black ph3 ph4-l"].join(' ')}>
              <h1 className={[styles.heroHeadingText, "f6 f2-m f-subheadline-l fw6 tc"].join(' ')}><Link href="/">HOME</Link></h1>
            </div>
          </section>

        </div>
      </main>
         

    </div>
  );
};

export default About;
