import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useLocomotiveScroll } from 'react-locomotive-scroll';

import styles from '../styles/main/main.module.css';

const Home: NextPage = () => {

  const { scroll } = useLocomotiveScroll();

  return (
    <div className={styles.container}>
      <Head>
        <title>VOID CULTURA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={[styles.main, ""].join(' ')}>
        <div data-scroll-section>
          <section id="firstSection" className={[styles.hero, "vh-100 dt w-100 bg-white relative z-0"].join(' ')} data-scroll data-scroll-speed="-8">
            <div className={[styles.heroContainer, "w-100 fixed top-1 center tc black ph3 ph4-l"].join(' ')}>
              <h1 className={[styles.heroHeadingText, "f6 fw6 tc"].join(' ')}><img src="/images/void.svg" alt="" className={[styles.hero, "logo"].join(' ')}/></h1>
            </div>
            <div className={[styles.heroContainer, "dtc v-mid tc black ph3 ph4-l"].join(' ')}>
              <h1 className={[styles.heroHeadingText, "ttu f3 f2-m f-subheadline-l fw6 tc"].join(' ')}>Promuoviamo le arti digitali attraverso la progettazione e la promozione di iniziative non convenzionali in ambito artistico e culturale.</h1>
            </div>
            <div className={[styles.heroContainer, "w-100 fixed bottom-1 left-0 center tc black ph3 ph4-l"].join(' ')}>
              <h1 className={[styles.heroHeadingText, "ttu f6 fw6 tc blinker"].join(' ')}>Scrolla</h1>
            </div>
          </section>

          <section id="secondSection" className={[styles.hero, "vh-75 vh-100-ns dt w-100 bg-void-green relative z-2"].join(' ')} data-scroll data-scroll-speed="0">
            <div className={[styles.heroContainer, "w-100 fixed top-1 left-0 center tc black ph3 ph4-l"].join(' ')}>
              <h1 className={[styles.heroInfoLinks, "f6 fw6 tc white"].join(' ')}><div className={["mr3"].join(' ')}><span>13/08/22</span></div><div className={["ttu mr3"].join(' ')}><span>Void City Hall 22</span></div></h1>
            </div>
            <div className={[styles.heroContainer, "dtc v-mid tc white ph3 ph4-l"].join(' ')}>
              <h1 className={[styles.heroHeadingText, "f6 f2-m f-subheadline-l fw6 tc"].join(' ')}><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 793.42 356.67"><defs></defs><g id="Livello_2" data-name="Livello 2"><g id="Livello_1-2" data-name="Livello 1"><polygon className={[styles.svgCls1, "cls-1"].join(' ')} points="582.24 196.03 621.91 196.03 621.91 85.07 618.84 75.09 582.24 196.03"/><path className={[styles.svgCls1, "cls-1"].join(' ')} d="M547.48,135c0,27.36,5.8,52.54,17.27,74.94l28.8-94.68c-1.87-6.24-4.32-9.49-7.31-9.68l-3.37,1c-4.74,1.15-8.91,8.21-12.12,20.42l-4.85,18.44V126.13c0-16.69,2.69-30.09,8-39.83,5.1-9.15,12-13.78,20.4-13.78A31,31,0,0,1,606,74.72l4.2-14.1c-7.84-7-15.35-10.62-22.35-10.62-11,0-20.08,7.35-27.7,22.46C551.73,88.6,547.48,109.61,547.48,135Z"/><polygon className={[styles.svgCls1, "cls-1"].join(' ')} points="561.52 262.33 605.34 307.61 622.84 275.85 622.84 237.86 568.99 237.86 561.52 262.33"/><path className={[styles.svgCls2, "cls-2"].join(' ')} d="M40.56,3.45C26.93,3.45,17.14,14.53,9.9,50.21,3.42,82.14,0,126.44,0,178.32c0,55-.63,175.74,40.56,175.74,7.44,0,23,2.69,30.89-17.93,6.33-16.59,9.67-41,9.67-70.65V250.9H58.4v14.58c0,33.43-5.93,42.36-9.44,42.36-2.45,0-6.93-4-9.43-31.15-2.07-22.46-2.35-56.13-2.35-89.17,0-85.37,1.77-138.28,10.61-138.28,2.19,0,7.29,3.36,7.29,34.48v23.77H80.54V3.45h0"/><polygon className={[styles.svgCls2, "cls-2"].join(' ')} points="90.23 107.93 103.12 107.93 103.12 249.59 90.23 249.59 90.23 354.06 165.5 354.06 165.5 249.59 152.41 249.59 152.41 107.93 165.5 107.93 165.5 3.45 90.23 3.45 90.23 107.93"/><polygon className={[styles.svgCls2, "cls-2"].join(' ')} points="173.44 139.02 181.95 139.02 196.01 33.48 198.44 33.48 198.44 319.56 186.13 346.27 186.13 354.06 233.85 354.06 233.85 346.23 220.57 319.51 220.57 33.48 223.54 33.48 235.84 139.02 244.4 139.02 244.4 3.45 173.44 3.45 173.44 139.02"/><polygon className={[styles.svgCls2, "cls-2"].join(' ')} points="336.91 58.88 358.79 58.88 358.79 101.56 336.91 101.56 336.91 151.04 320.38 151.04 320.38 101.56 298.31 101.56 298.31 58.88 320.38 58.88 320.38 3.45 249.22 3.45 249.22 58.88 271.09 58.88 271.09 107.93 292.97 107.93 292.97 157.42 315.04 157.42 315.04 298.64 292.97 298.64 292.97 354.06 364.13 354.06 364.13 298.64 342.25 298.64 342.25 157.42 364.13 157.42 364.13 107.93 386.19 107.93 386.19 58.88 408.07 58.88 408.07 3.45 336.91 3.45 336.91 58.88"/><polygon className={[styles.svgCls2, "cls-2"].join(' ')} points="497.85 80.53 486 80.53 486 3.45 418.75 3.45 418.75 354.06 486 354.06 486 131.14 497.85 131.14 497.85 354.06 525.84 354.06 525.84 3.45 497.85 3.45 497.85 80.53"/><polygon className={[styles.svgCls2, "cls-2"].join(' ')} points="729.76 3.45 694.13 3.45 668.34 354.06 729.93 354.06 735.43 282 709.25 282 729.76 3.45"/><polygon className={[styles.svgCls2, "cls-2"].join(' ')} points="780.33 298.64 780.33 3.45 740.03 3.45 740.03 354.06 793.41 354.06 793.41 298.64 780.33 298.64"/><path className={[styles.svgCls2, "cls-2"].join(' ')} d="M665.26,289.17,658,301.46c-3-9.55-4.68-24.69-4.94-45.11L651.16,80.43a157.92,157.92,0,0,1,5-41.72,151.85,151.85,0,0,1,5-14.76c2.14-5.47,4.76-11.53,7.79-18l.58-1.24L667.41,0,665.2,1.18c-9.48,5.06-18.09,16.64-25.6,34.45-14.51-21-30-31.61-46-31.61-17,0-31.21,12.74-42.26,37.88-10.76,24.83-16.22,52.47-16.22,82.15l.47,11.55c1.23,28.68,9.41,59.1,24.32,90.42l-20.27,67.4c-5.45,18.52-8.22,33.3-8.22,43.93S534,353.59,539,353.59c3.66,0,8-2.37,8-13.65a68.72,68.72,0,0,0-1.21-10.9,60.2,60.2,0,0,1-1.11-9.34,23.29,23.29,0,0,1,1.71-9.42c.79-1.78,1.67-2.88,2.3-2.88s3.12.62,7.91,6.4l35,41.45,31.86-53.34c3.07,23.33,8.63,40.7,16.56,51.69l2.23,3.07,28.88-53.41Zm-42.42-13.32-17.5,31.76-43.82-45.28L569,237.86h53.85ZM587.82,50c7,0,14.51,3.57,22.35,10.62L606,74.72a31,31,0,0,0-11.67-2.2c-8.44,0-15.3,4.63-20.4,13.78-5.31,9.74-8,23.14-8,39.83v19.21l4.85-18.44c3.21-12.21,7.38-19.27,12.12-20.42l3.37-1c3,.19,5.44,3.44,7.31,9.68l-28.8,94.68c-11.47-22.4-17.27-47.58-17.27-74.94,0-25.34,4.25-46.35,12.64-62.49C567.74,57.35,576.8,50,587.82,50Zm34.09,146H582.24l36.6-120.94,3.07,10Z"/></g></g></svg></h1>
            </div>
            <div className={[styles.heroContainer, "w-100 fixed bottom-1 left-0 center tc black ph3 ph4-l"].join(' ')}>
              <h1 className={[styles.heroInfoLinks, "f6 fw6 tc white"].join(' ')}><div className={["ttu mr3 no-drop"].join(' ')}><span><Link href="https://www.instagram.com/p/CgxIJxuI9x-/" passHref><a target="_blank" rel="noopener noreferrer">Instagram</a></Link></span></div><div className={["ttu mr3 alias"].join(' ')}><span><Link href="https://www.facebook.com/voidcultura/posts/pfbid0DfeQvrzBHDJBtfaQdxaM7FoK5Z5bnsTrD8tYef5SJm1Vs38zpV8EAoSVeBvYxZBnl" passHref><a target="_blank" rel="noopener noreferrer">Facebook</a></Link></span></div></h1>
            </div>
          </section>

          <section id="thirdSection" className={[styles.hero, "vh-75 dt w-100 bg-white relative z-1"].join(' ')} data-scroll data-scroll-speed="2" data-scroll-target="#thirdSection">
            <div className={[styles.heroContainer, "dtc v-mid tc black ph3 ph4-l"].join(' ')}>
              <h1 className={[styles.heroHeadingText, "ttu f6 f2-m f-subheadline-l fw6 tc mv0"].join(' ')}><Link href="mailto:info@voidcultura.org">info@voidcultura.org</Link></h1>
              <h1 className={[styles.heroHeadingText, "ttu f6 f2-m f-subheadline-l fw6 tc mv0"].join(' ')}><Link href="https://instagram.com/voidcultura" passHref><a target="_blank" rel="noopener noreferrer">Instagram</a></Link> / <Link href="https://facebook.com/voidcultura"><a target="_blank" rel="noopener noreferrer">Facebook</a></Link></h1>

            </div>
          </section>

          <footer id="footerSection" data-scroll data-scroll-speed="-4" data-scroll-target="#footerSection" data-scroll-position="bottom">
            <div className={[styles.footer, "vh-25 dt w-100 bg-black relative z-0"].join(' ')}>
              <div className={[styles.footerContainer, "dtc v-mid tc white ph3 ph4-l"].join(' ')}>
                <h1 className={[styles.footerText, "ttu f6 tc mv0"].join(' ')}>Sito in Costruzione</h1>
                <h1 className={[styles.footerText, "ttu f6 tc mv0"].join(' ')}>© Void Cultura 2019-2022</h1>
              </div>
            </div>
          </footer>

        </div>
      </main>
         

    </div>
  );
};

export default Home;
